import { partOne } from "./solution";

describe("Part one", () => {
  it("it should find the shortest path between all galaxies ", () => {
    expect(
      partOne(`
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
`),
    ).toBe(374);
  });
});
